package database

// baseSchema ينشئ كل الجداول والأنواع من الصفر لو قاعدة البيانات فاضية — آمن يشتغل
// أكثر من مرة (كل شي IF NOT EXISTS).
var baseSchema = []string{
	// ---- Enums ----
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ProjectPriority') THEN CREATE TYPE "ProjectPriority" AS ENUM ('NORMAL','URGENT'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'BookingStatus') THEN CREATE TYPE "BookingStatus" AS ENUM ('IN_PROGRESS','PENDING','CONFIRMED','COMPLETED','CANCELLED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EquipmentStatus') THEN CREATE TYPE "EquipmentStatus" AS ENUM ('NOT_READY','READY'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Shift') THEN CREATE TYPE "Shift" AS ENUM ('MORNING','EVENING'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'TechnicianRole') THEN CREATE TYPE "TechnicianRole" AS ENUM ('TECH_1','TECH_2','TECH_3'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EmployeeStatus') THEN CREATE TYPE "EmployeeStatus" AS ENUM ('ACTIVE','INACTIVE'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EmployeeRole') THEN CREATE TYPE "EmployeeRole" AS ENUM ('ADMIN','SALES','HR_COORDINATOR','TECHNICIAN','PROJECT_MANAGER','MONITOR','FINANCE','GPS_ADMIN','GPS_ENGINEER','QUALITY_ENGINEER','ENGINEER'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ExpenseStatus') THEN CREATE TYPE "ExpenseStatus" AS ENUM ('PENDING','APPROVED','REJECTED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ToolStatus') THEN CREATE TYPE "ToolStatus" AS ENUM ('AVAILABLE','CHECKED_OUT','DAMAGED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ToolRequestStatus') THEN CREATE TYPE "ToolRequestStatus" AS ENUM ('PENDING','APPROVED','REJECTED','RETURNED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ComplaintStatus') THEN CREATE TYPE "ComplaintStatus" AS ENUM ('NEW','IN_PROGRESS','RESOLVED','CLOSED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SimOperator') THEN CREATE TYPE "SimOperator" AS ENUM ('ZAIN','ASIACELL','KOREK','OTHER'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SimStatus') THEN CREATE TYPE "SimStatus" AS ENUM ('AVAILABLE','IN_USE'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GpsRequestStatus') THEN CREATE TYPE "GpsRequestStatus" AS ENUM ('PENDING','APPROVED','REJECTED','DELIVERED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GpsPurchaseType') THEN CREATE TYPE "GpsPurchaseType" AS ENUM ('DEVICE_SIM','DEVICE_ONLY'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GpsSubscriptionType') THEN CREATE TYPE "GpsSubscriptionType" AS ENUM ('THREE_MONTHS','SIX_MONTHS','YEARLY'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GpsSubscriptionStatus') THEN CREATE TYPE "GpsSubscriptionStatus" AS ENUM ('ACTIVE','EXPIRED','CANCELLED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GpsMaintenanceStatus') THEN CREATE TYPE "GpsMaintenanceStatus" AS ENUM ('PENDING','IN_PROGRESS','COMPLETED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'QuotationStatus') THEN CREATE TYPE "QuotationStatus" AS ENUM ('NEW','SENT','ACCEPTED','REJECTED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ProcurementRequestStatus') THEN CREATE TYPE "ProcurementRequestStatus" AS ENUM ('PENDING','IN_PROGRESS','FULFILLED','REJECTED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'BookingType') THEN CREATE TYPE "BookingType" AS ENUM ('REGULAR','MAINTENANCE'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'BookingUrgency') THEN CREATE TYPE "BookingUrgency" AS ENUM ('ASAP','BY_PRIORITY','SPECIFIC_DATE'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'MaintenanceType') THEN CREATE TYPE "MaintenanceType" AS ENUM ('EXECUTION_ERROR','DEVICE_ISSUE'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'WorkStatus') THEN CREATE TYPE "WorkStatus" AS ENUM ('COMPLETED','STOPPED'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ProjectSpeed') THEN CREATE TYPE "ProjectSpeed" AS ENUM ('URGENT','INTERNAL','REGULAR','DIRECTOR_REQ'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'WorkType') THEN CREATE TYPE "WorkType" AS ENUM ('FREE_MAINTENANCE','PAID'); END IF; END $$`,
	`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'MissionStage') THEN CREATE TYPE "MissionStage" AS ENUM ('ASSIGNED','MATERIALS_PREP','MATERIALS_READY','EN_ROUTE','ARRIVED','WORK_STARTED','COMPLETED','STOPPED'); END IF; END $$`,

	// ---- Tables ----
	`CREATE TABLE IF NOT EXISTS "Service" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		category TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "TrainingMaterial" (
		id TEXT PRIMARY KEY,
		"serviceId" TEXT NOT NULL REFERENCES "Service"(id) ON DELETE CASCADE,
		title TEXT NOT NULL,
		url TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'VIDEO',
		"order" INTEGER NOT NULL DEFAULT 0,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "Customer" (
		id TEXT PRIMARY KEY,
		"customerCode" SERIAL UNIQUE,
		name TEXT NOT NULL,
		phone TEXT NOT NULL UNIQUE,
		location TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "Employee" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		certificate TEXT,
		position TEXT,
		phone TEXT,
		status "EmployeeStatus" NOT NULL DEFAULT 'ACTIVE',
		role "EmployeeRole" NOT NULL DEFAULT 'TECHNICIAN',
		"onDuty" BOOLEAN NOT NULL DEFAULT true,
		username TEXT UNIQUE,
		password TEXT,
		"hasDrivingLicense" BOOLEAN NOT NULL DEFAULT false,
		"hasSafetyCertificate" BOOLEAN NOT NULL DEFAULT false,
		salary DOUBLE PRECISION,
		shift "Shift" DEFAULT 'MORNING',
		"monthlyLeaves" INTEGER NOT NULL DEFAULT 2,
		"jobTitle" TEXT,
		"leaderSkillLevel" INTEGER NOT NULL DEFAULT 0,
		"isLeader" BOOLEAN NOT NULL DEFAULT false,
		"isTrainee" BOOLEAN NOT NULL DEFAULT false,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "EmployeeTrainingAssignment" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id) ON DELETE CASCADE,
		"serviceId" TEXT NOT NULL REFERENCES "Service"(id) ON DELETE CASCADE,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE ("employeeId", "serviceId")
	)`,
	`CREATE TABLE IF NOT EXISTS "Skill" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		"serviceId" TEXT NOT NULL REFERENCES "Service"(id) ON DELETE CASCADE,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE ("serviceId", name)
	)`,
	`CREATE INDEX IF NOT EXISTS "Skill_serviceId_idx" ON "Skill"("serviceId")`,
	`CREATE TABLE IF NOT EXISTS "EmployeeSkill" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id) ON DELETE CASCADE,
		"skillId" TEXT NOT NULL REFERENCES "Skill"(id) ON DELETE CASCADE,
		"canPerform" BOOLEAN NOT NULL DEFAULT true,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE ("employeeId", "skillId")
	)`,
	`CREATE INDEX IF NOT EXISTS "EmployeeSkill_skillId_idx" ON "EmployeeSkill"("skillId")`,
	`CREATE TABLE IF NOT EXISTS "Booking" (
		id TEXT PRIMARY KEY,
		code TEXT NOT NULL UNIQUE,
		"sequenceNumber" INTEGER,
		"scheduledAt" TIMESTAMP,
		"customerId" TEXT NOT NULL REFERENCES "Customer"(id),
		"serviceId" TEXT REFERENCES "Service"(id),
		notes TEXT,
		"vehicleType" TEXT,
		priority "ProjectPriority" NOT NULL DEFAULT 'NORMAL',
		status "BookingStatus" NOT NULL DEFAULT 'PENDING',
		"transferEmployeeId" TEXT REFERENCES "Employee"(id),
		"transferToProjects" BOOLEAN NOT NULL DEFAULT false,
		"confirmedByName" TEXT,
		"confirmedByEmployeeId" TEXT REFERENCES "Employee"(id),
		"adminNotes" TEXT,
		"equipmentStatus" "EquipmentStatus" NOT NULL DEFAULT 'NOT_READY',
		shift "Shift",
		"deviceCount" INTEGER,
		"inspectionSupervisorId" TEXT REFERENCES "Employee"(id),
		"projectSupervisorId" TEXT REFERENCES "Employee"(id),
		"projectCar" TEXT,
		"crewNotes" TEXT,
		"mapLocation" TEXT,
		"expenseResponsibleId" TEXT REFERENCES "Employee"(id),
		"assignedVehicle" TEXT,
		"quotedPrice" DOUBLE PRECISION,
		address TEXT,
		"completedAt" TIMESTAMP,
		"completionNotes" TEXT,
		"amountCollected" DOUBLE PRECISION,
		"advancePaid" DOUBLE PRECISION,
		"amountVerified" BOOLEAN NOT NULL DEFAULT false,
		"bookingType" "BookingType" NOT NULL DEFAULT 'REGULAR',
		urgency "BookingUrgency",
		"maintenanceType" "MaintenanceType",
		"remembersExecutionCrew" BOOLEAN NOT NULL DEFAULT false,
		"systemCount" INTEGER,
		"systemType" TEXT,
		"projectSpeed" "ProjectSpeed",
		"workType" "WorkType",
		"addressDescription" TEXT,
		"mapLatitude" DOUBLE PRECISION,
		"mapLongitude" DOUBLE PRECISION,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "Booking_customerId_idx" ON "Booking"("customerId")`,
	`CREATE INDEX IF NOT EXISTS "Booking_serviceId_idx" ON "Booking"("serviceId")`,
	`CREATE INDEX IF NOT EXISTS "Booking_status_idx" ON "Booking"(status)`,
	`CREATE TABLE IF NOT EXISTS "BookingAssignment" (
		id TEXT PRIMARY KEY,
		"bookingId" TEXT NOT NULL REFERENCES "Booking"(id) ON DELETE CASCADE,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		role "TechnicianRole" NOT NULL,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE ("bookingId", role)
	)`,
	`CREATE INDEX IF NOT EXISTS "BookingAssignment_employeeId_idx" ON "BookingAssignment"("employeeId")`,
	`CREATE TABLE IF NOT EXISTS "ScheduleChangeLog" (
		id TEXT PRIMARY KEY,
		"bookingId" TEXT NOT NULL REFERENCES "Booking"(id) ON DELETE CASCADE,
		"changedById" TEXT NOT NULL REFERENCES "Employee"(id),
		"oldTime" TIMESTAMP,
		"newTime" TIMESTAMP NOT NULL,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "ScheduleChangeLog_bookingId_idx" ON "ScheduleChangeLog"("bookingId")`,
	`CREATE INDEX IF NOT EXISTS "ScheduleChangeLog_changedById_idx" ON "ScheduleChangeLog"("changedById")`,
	`CREATE TABLE IF NOT EXISTS "Permission" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		label TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS "EmployeePermission" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id) ON DELETE CASCADE,
		"permissionId" TEXT NOT NULL REFERENCES "Permission"(id) ON DELETE CASCADE,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE ("employeeId", "permissionId")
	)`,
	`CREATE TABLE IF NOT EXISTS "KpiEvaluation" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"evaluatorId" TEXT NOT NULL REFERENCES "Employee"(id),
		points INTEGER NOT NULL,
		reason TEXT NOT NULL,
		"deductionAmount" DOUBLE PRECISION NOT NULL,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "KpiEvaluation_employeeId_idx" ON "KpiEvaluation"("employeeId")`,
	`CREATE TABLE IF NOT EXISTS "CartItem" (
		id TEXT PRIMARY KEY,
		"bookingId" TEXT NOT NULL REFERENCES "Booking"(id) ON DELETE CASCADE,
		"productName" TEXT NOT NULL,
		quantity INTEGER NOT NULL,
		"unitPrice" DOUBLE PRECISION NOT NULL,
		"totalPrice" DOUBLE PRECISION NOT NULL,
		notes TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "CartItem_bookingId_idx" ON "CartItem"("bookingId")`,
	`CREATE TABLE IF NOT EXISTS "Expense" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		amount DOUBLE PRECISION NOT NULL,
		description TEXT,
		status "ExpenseStatus" NOT NULL DEFAULT 'PENDING',
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "Expense_employeeId_idx" ON "Expense"("employeeId")`,
	`CREATE TABLE IF NOT EXISTS "PersonalTool" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		name TEXT NOT NULL,
		barcode TEXT NOT NULL UNIQUE,
		status "ToolStatus" NOT NULL DEFAULT 'AVAILABLE',
		"checkedOut" BOOLEAN NOT NULL DEFAULT false,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "PersonalTool_employeeId_idx" ON "PersonalTool"("employeeId")`,
	`CREATE TABLE IF NOT EXISTS "VehicleTool" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		barcode TEXT NOT NULL UNIQUE,
		"vehicleId" TEXT NOT NULL,
		status "ToolStatus" NOT NULL DEFAULT 'AVAILABLE',
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "VehicleTool_vehicleId_idx" ON "VehicleTool"("vehicleId")`,
	`CREATE TABLE IF NOT EXISTS "OnDemandTool" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		barcode TEXT NOT NULL UNIQUE,
		"totalQuantity" INTEGER NOT NULL,
		"availableQuantity" INTEGER NOT NULL,
		status "ToolStatus" NOT NULL DEFAULT 'AVAILABLE',
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "ToolRequest" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"toolId" TEXT NOT NULL REFERENCES "OnDemandTool"(id),
		status "ToolRequestStatus" NOT NULL DEFAULT 'PENDING',
		"approvedById" TEXT REFERENCES "Employee"(id),
		"requestedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"returnedAt" TIMESTAMP
	)`,
	`ALTER TABLE "ToolRequest" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP`,
	`CREATE INDEX IF NOT EXISTS "ToolRequest_employeeId_idx" ON "ToolRequest"("employeeId")`,
	`CREATE INDEX IF NOT EXISTS "ToolRequest_toolId_idx" ON "ToolRequest"("toolId")`,
	`CREATE TABLE IF NOT EXISTS "Complaint" (
		id TEXT PRIMARY KEY,
		"customerId" TEXT NOT NULL REFERENCES "Customer"(id),
		"bookingId" TEXT REFERENCES "Booking"(id),
		description TEXT NOT NULL,
		status "ComplaintStatus" NOT NULL DEFAULT 'NEW',
		"createdByEmployeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"assignedToEmployeeId" TEXT REFERENCES "Employee"(id),
		resolution TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"resolvedAt" TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "Complaint_customerId_idx" ON "Complaint"("customerId")`,
	`CREATE INDEX IF NOT EXISTS "Complaint_status_idx" ON "Complaint"(status)`,
	`CREATE TABLE IF NOT EXISTS "GpsCustomer" (
		id TEXT PRIMARY KEY,
		"fullName" TEXT NOT NULL,
		"fatherName" TEXT,
		"grandfatherName" TEXT,
		phone TEXT NOT NULL,
		address TEXT,
		governorate TEXT,
		"idCardFrontUrl" TEXT,
		"idCardBackUrl" TEXT,
		"residenceCardFrontUrl" TEXT,
		"residenceCardBackUrl" TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "SimCard" (
		id TEXT PRIMARY KEY,
		"simNumber" TEXT NOT NULL UNIQUE,
		iccid TEXT,
		operator "SimOperator" NOT NULL,
		status "SimStatus" NOT NULL DEFAULT 'AVAILABLE',
		"customerId" TEXT REFERENCES "GpsCustomer"(id),
		notes TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "SimCard_status_idx" ON "SimCard"(status)`,
	`CREATE TABLE IF NOT EXISTS "GpsDeviceRequest" (
		id TEXT PRIMARY KEY,
		"customerId" TEXT NOT NULL REFERENCES "GpsCustomer"(id),
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"adminId" TEXT REFERENCES "Employee"(id),
		"purchaseType" "GpsPurchaseType" NOT NULL,
		"subscriptionType" "GpsSubscriptionType" NOT NULL,
		"subscriptionStart" TIMESTAMP,
		"subscriptionEnd" TIMESTAMP,
		"subscriptionStatus" "GpsSubscriptionStatus" NOT NULL DEFAULT 'ACTIVE',
		status "GpsRequestStatus" NOT NULL DEFAULT 'PENDING',
		"simCardId" TEXT REFERENCES "SimCard"(id),
		notes TEXT,
		"isChecked" BOOLEAN NOT NULL DEFAULT false,
		"isActivated" BOOLEAN NOT NULL DEFAULT false,
		"isDelivered" BOOLEAN NOT NULL DEFAULT false,
		"invoicePhotoUrl" TEXT,
		"gpsNumber" TEXT,
		"residenceCardNumber" TEXT,
		"activationDate" TIMESTAMP,
		"deliveredAt" TIMESTAMP,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "GpsDeviceRequest_customerId_idx" ON "GpsDeviceRequest"("customerId")`,
	`CREATE INDEX IF NOT EXISTS "GpsDeviceRequest_status_idx" ON "GpsDeviceRequest"(status)`,
	`CREATE TABLE IF NOT EXISTS "GpsRenewalRequest" (
		id TEXT PRIMARY KEY,
		"customerId" TEXT NOT NULL REFERENCES "GpsCustomer"(id),
		"deviceRequestId" TEXT NOT NULL REFERENCES "GpsDeviceRequest"(id),
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"adminId" TEXT REFERENCES "Employee"(id),
		"subscriptionType" "GpsSubscriptionType" NOT NULL,
		"newEndDate" TIMESTAMP,
		status "GpsRequestStatus" NOT NULL DEFAULT 'PENDING',
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "GpsRenewalRequest_customerId_idx" ON "GpsRenewalRequest"("customerId")`,
	`CREATE TABLE IF NOT EXISTS "GpsMaintenanceRequest" (
		id TEXT PRIMARY KEY,
		"customerId" TEXT NOT NULL REFERENCES "GpsCustomer"(id),
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"adminId" TEXT REFERENCES "Employee"(id),
		"problemDescription" TEXT NOT NULL,
		status "GpsMaintenanceStatus" NOT NULL DEFAULT 'PENDING',
		"adminNotes" TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"resolvedAt" TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "GpsMaintenanceRequest_customerId_idx" ON "GpsMaintenanceRequest"("customerId")`,
	`CREATE TABLE IF NOT EXISTS "GpsSubscriptionPrice" (
		id TEXT PRIMARY KEY,
		"subscriptionType" "GpsSubscriptionType" NOT NULL UNIQUE,
		price DOUBLE PRECISION NOT NULL,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "Product" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		unit TEXT,
		"defaultPrice" DOUBLE PRECISION,
		"imageBase64" TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "Quotation" (
		id TEXT PRIMARY KEY,
		"quotationNumber" TEXT NOT NULL UNIQUE,
		"customerName" TEXT NOT NULL,
		"customerPhone" TEXT,
		"customerAddress" TEXT,
		"projectName" TEXT,
		"grandTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
		"discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
		"discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
		"netTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
		notes TEXT,
		duration TEXT,
		status "QuotationStatus" NOT NULL DEFAULT 'NEW',
		"createdByEmployeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "Quotation_status_idx" ON "Quotation"(status)`,
	`CREATE TABLE IF NOT EXISTS "QuotationItem" (
		id TEXT PRIMARY KEY,
		"quotationId" TEXT NOT NULL REFERENCES "Quotation"(id) ON DELETE CASCADE,
		"productName" TEXT NOT NULL,
		unit TEXT,
		quantity INTEGER NOT NULL,
		"unitPrice" DOUBLE PRECISION NOT NULL,
		"totalPrice" DOUBLE PRECISION NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS "QuotationItem_quotationId_idx" ON "QuotationItem"("quotationId")`,
	`CREATE TABLE IF NOT EXISTS "Attendance" (
		id TEXT PRIMARY KEY,
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"checkIn" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"checkOut" TIMESTAMP,
		date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE ("employeeId", date)
	)`,
	`CREATE INDEX IF NOT EXISTS "Attendance_employeeId_idx" ON "Attendance"("employeeId")`,
	`CREATE INDEX IF NOT EXISTS "Attendance_date_idx" ON "Attendance"(date)`,
	`CREATE TABLE IF NOT EXISTS "WorkReport" (
		id TEXT PRIMARY KEY,
		"bookingId" TEXT NOT NULL REFERENCES "Booking"(id),
		"employeeId" TEXT NOT NULL REFERENCES "Employee"(id),
		"workStatus" "WorkStatus" NOT NULL,
		events TEXT,
		"extraRequests" TEXT,
		"cleanedSite" BOOLEAN NOT NULL DEFAULT false,
		"gaveInfo" BOOLEAN NOT NULL DEFAULT false,
		"tookPhotos" BOOLEAN NOT NULL DEFAULT false,
		"stopReason" TEXT,
		notes TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "WorkReport_bookingId_idx" ON "WorkReport"("bookingId")`,
	`CREATE INDEX IF NOT EXISTS "WorkReport_employeeId_idx" ON "WorkReport"("employeeId")`,
	`CREATE TABLE IF NOT EXISTS "Vehicle" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		"plateNumber" TEXT NOT NULL UNIQUE,
		color TEXT,
		type TEXT,
		"isActive" BOOLEAN NOT NULL DEFAULT true,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "SupplierSpecialty" (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		"order" INTEGER NOT NULL DEFAULT 0,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "Supplier" (
		id TEXT PRIMARY KEY,
		"companyName" TEXT NOT NULL,
		"ownerName" TEXT NOT NULL,
		phone TEXT NOT NULL,
		lat DOUBLE PRECISION,
		lng DOUBLE PRECISION,
		"isMaterialSupplier" BOOLEAN NOT NULL DEFAULT false,
		"isContractor" BOOLEAN NOT NULL DEFAULT false,
		"traderTypes" TEXT[] DEFAULT '{}',
		notes TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS "SupplierSpecialtyLink" (
		"supplierId" TEXT NOT NULL REFERENCES "Supplier"(id) ON DELETE CASCADE,
		"specialtyId" TEXT NOT NULL REFERENCES "SupplierSpecialty"(id) ON DELETE CASCADE,
		PRIMARY KEY ("supplierId", "specialtyId")
	)`,
	`CREATE TABLE IF NOT EXISTS "SupplierRating" (
		id TEXT PRIMARY KEY,
		"supplierId" TEXT NOT NULL REFERENCES "Supplier"(id) ON DELETE CASCADE,
		value INTEGER NOT NULL,
		note TEXT,
		"ratedById" TEXT NOT NULL REFERENCES "Employee"(id),
		"ratedByName" TEXT NOT NULL,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "SupplierRating_supplierId_idx" ON "SupplierRating"("supplierId")`,
	`CREATE TABLE IF NOT EXISTS "Mission" (
		id TEXT PRIMARY KEY,
		code TEXT NOT NULL UNIQUE,
		"bookingId" TEXT NOT NULL REFERENCES "Booking"(id),
		stage "MissionStage" NOT NULL DEFAULT 'ASSIGNED',
		"leaderId" TEXT NOT NULL,
		"memberIds" TEXT[] DEFAULT '{}',
		"customerLat" DOUBLE PRECISION,
		"customerLng" DOUBLE PRECISION,
		"customerAddress" TEXT,
		"assignedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"materialsReadyAt" TIMESTAMP,
		"departedAt" TIMESTAMP,
		"arrivedAt" TIMESTAMP,
		"workStartedAt" TIMESTAMP,
		"completedAt" TIMESTAMP,
		"stoppedAt" TIMESTAMP,
		"departureLat" DOUBLE PRECISION,
		"departureLng" DOUBLE PRECISION,
		"arrivalLat" DOUBLE PRECISION,
		"arrivalLng" DOUBLE PRECISION,
		"estimatedMinutes" INTEGER,
		"actualMinutes" INTEGER,
		"distanceKm" DOUBLE PRECISION,
		"stopReason" TEXT,
		notes TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "Mission_bookingId_idx" ON "Mission"("bookingId")`,
	`CREATE INDEX IF NOT EXISTS "Mission_stage_idx" ON "Mission"(stage)`,
	`CREATE INDEX IF NOT EXISTS "Mission_leaderId_idx" ON "Mission"("leaderId")`,
	`CREATE TABLE IF NOT EXISTS "MissionEvent" (
		id TEXT PRIMARY KEY,
		"missionId" TEXT NOT NULL REFERENCES "Mission"(id) ON DELETE CASCADE,
		"employeeId" TEXT NOT NULL,
		action TEXT NOT NULL,
		lat DOUBLE PRECISION,
		lng DOUBLE PRECISION,
		note TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "MissionEvent_missionId_idx" ON "MissionEvent"("missionId")`,
	`CREATE TABLE IF NOT EXISTS "Project" (
		id TEXT PRIMARY KEY,
		code TEXT NOT NULL UNIQUE,
		name TEXT NOT NULL,
		rep TEXT,
		phone TEXT,
		location TEXT,
		"workType" TEXT,
		"refPerson" TEXT,
		stage TEXT NOT NULL DEFAULT '1. اتصال بالزبون',
		price TEXT,
		staff TEXT,
		time TEXT,
		task TEXT,
		priority TEXT NOT NULL DEFAULT 'عادي',
		"deliveryDate" TEXT,
		survey JSONB,
		"sentToGroup" BOOLEAN NOT NULL DEFAULT false,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "Project_stage_idx" ON "Project"(stage)`,
	`CREATE TABLE IF NOT EXISTS "ProcurementRequest" (
		id TEXT PRIMARY KEY,
		code TEXT NOT NULL UNIQUE,
		"requestedById" TEXT NOT NULL REFERENCES "Employee"(id),
		"bookingId" TEXT REFERENCES "Booking"(id),
		notes TEXT,
		status "ProcurementRequestStatus" NOT NULL DEFAULT 'PENDING',
		"fulfilledById" TEXT REFERENCES "Employee"(id),
		"totalCost" DOUBLE PRECISION,
		"fulfillmentNotes" TEXT,
		"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		"fulfilledAt" TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS "ProcurementRequest_requestedById_idx" ON "ProcurementRequest"("requestedById")`,
	`CREATE INDEX IF NOT EXISTS "ProcurementRequest_status_idx" ON "ProcurementRequest"(status)`,
	`CREATE TABLE IF NOT EXISTS "ProcurementItem" (
		id TEXT PRIMARY KEY,
		"requestId" TEXT NOT NULL REFERENCES "ProcurementRequest"(id) ON DELETE CASCADE,
		"productName" TEXT NOT NULL,
		quantity INTEGER NOT NULL,
		"unitPrice" DOUBLE PRECISION,
		"totalPrice" DOUBLE PRECISION,
		fulfilled BOOLEAN NOT NULL DEFAULT false
	)`,
	`CREATE INDEX IF NOT EXISTS "ProcurementItem_requestId_idx" ON "ProcurementItem"("requestId")`,
}
